## Imported data from OpenTriviaDB
question_data = [
    {"type": "boolean",
     "difficulty": "medium",
     "category": "Entertainment: Music",
     "question": "Rumble; by Link Wray is the only instrumental song to ever have been banned from US radio.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "medium",
     "category": "Vehicles",
     "question": "Mitsubishi Motors has had a 30-year partnership with Jackie Chan, whose movies have prominently featured their vehicles.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "medium", "category": "History",
     "question": "Theodore Roosevelt Jr. was the only General involved in the initial assault on D-Day.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science &amp; Nature",
     "question": "Hippopotomonstrosesquippedaliophobia is the irrational fear of long words.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Mathematics",
     "question": "The Pythagorean theorem states that the square of the hypotenuse is equal to the product of the squares of the other two sides.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "In Full Metal Panic!, Whispered are those who are capable of creating Black Technology.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Art",
     "question": "Vincent van Gogh cut off one of his ears.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
     "question": "The band, HEALTH, is called HEALTH because they wanted to choose an everyday word for the band name.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Geography",
     "question": "The flag of South Africa features 7 colours.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "medium",
     "category": "Geography",
     "question": "Route 66 in the United States spans the entire mainland of America, from California to New York.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]}]

